# Generated by Django 5.0.2 on 2024-05-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
        ('vendor', '0002_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='acknowledgement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='items',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='vendor.vendor'),
        ),
    ]
