# Generated by Django 5.0.2 on 2024-05-03 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchase_acknowledgement_date_and_more'),
        ('vendor', '0002_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='vendor.vendor'),
        ),
    ]
