# Generated by Django 5.0.4 on 2024-05-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchase_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='po_number',
            field=models.CharField(blank=True, help_text='Will be alloted automatically once the Order is  Created', max_length=100, null=True, verbose_name='Unique Product Order No'),
        ),
    ]
