# Generated by Django 5.0.4 on 2024-05-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchase_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
