# Generated by Django 5.0.4 on 2024-05-05 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_purchase_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='acknowledgement_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expected Delivery Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='po_number',
            field=models.CharField(blank=True, help_text='Will be alloted automatically once the Order is Created', max_length=100, null=True, verbose_name='Unique Product Order No'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100),
        ),
    ]
