# Generated by Django 5.0.4 on 2024-05-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_purchase_acknowledgement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='acknowledgement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
